<?php

return [
    'NOT_ACTIVE' => 0,
    'ACTIVATED' => 1,
    'AVATAR' => 'AVATAR',
    'PAGINATE' => 5,
    'OWNER' => 1,
    'NOT_OWNER' => 0,
    'RATING_CAMPAIGN' => 1,
    'RATING_USER' => 2,
    'ONE_STAR' => 1,
    'TWO_STAR' => 2,
    'THREE_STAR' => 3,
    'FOUR_STAR' => 4,
    'TOP_USER' => 4,
    'FIVE_STAR' => 5,
    'ROUND_CHART' => 2,
    'EMPTY_DATA' => 0,
    'FOLLOW_USER' => 1,
    'ACTION' => [
        'ACTIVE_CAMPAIGN' => 1,
        'CLOSE_CAMPAIGN' => 2,
        'CONTRIBUTE' => 3,
    ],
    'PAGINATE_CAMPAIGN' => 12,
    'USER_LIMIT' => 8,
    'ALL_USER_LIMIT' => 16,
    'LIMIT_TITLE_CHARACTERS' => 50,
    'LIMIT_DESCRIPTION_CHARACTERS' => 135,
    'INDEX_CAMPAIGNS' => 3,
    'PHONE' => '+84 4 3795 5417',
];
